### ISSUE TITLE
Tensorflow throws a pb related error

### ISSUE THREAD

**Issue by VLucet** [bencevans/camtrapml#27]
Hi! I tried to take this package for a spin and got stuck at the step 
```py
from camtrapml.detection.models.megadetector import MegaDetectorV4_1
```
I get the following message
```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
 3. More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```
<details close>
<summary>The full trace</summary>
<br>
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vlucet/.cache/pypoetry/virtualenvs/camtrapmltest-FmJ6uYFH-py3.10/lib/python3.10/site-packages/camtrapml/detection/models/megadetector.py", line 23, in <module>
    from .tensorflow import TF1ODAPIFrozenModel
  File "/home/vlucet/.cache/pypoetry/virtualenvs/camtrapmltest-FmJ6uYFH-py3.10/lib/python3.10/site-packages/camtrapml/detection/models/tensorflow.py", line 11, in <module>
    import tensorflow as tf
  File "/home/vlucet/.cache/pypoetry/virtualenvs/camtrapmltest-FmJ6uYFH-py3.10/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/vlucet/.cache/pypoetry/virtualenvs/camtrapmltest-FmJ6uYFH-py3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/vlucet/.cache/pypoetry/virtualenvs/camtrapmltest-FmJ6uYFH-py3.10/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/vlucet/.cache/pypoetry/virtualenvs/camtrapmltest-FmJ6uYFH-py3.10/lib/python3.10/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/vlucet/.cache/pypoetry/virtualenvs/camtrapmltest-FmJ6uYFH-py3.10/lib/python3.10/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/vlucet/.cache/pypoetry/virtualenvs/camtrapmltest-FmJ6uYFH-py3.10/lib/python3.10/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/vlucet/.cache/pypoetry/virtualenvs/camtrapmltest-FmJ6uYFH-py3.10/lib/python3.10/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/vlucet/.cache/pypoetry/virtualenvs/camtrapmltest-FmJ6uYFH-py3.10/lib/python3.10/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/vlucet/.cache/pypoetry/virtualenvs/camtrapmltest-FmJ6uYFH-py3.10/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```
</details>

**Comment by bencevans** [comment]
Hi @VLucet 

Thanks for letting me know. I'll look into pinning dependency versions in the future. Could you try installing the 3.20.x version of the protobuf package to see if it does resolve it? ...

```
pip install protobuf==3.20
```

**Comment by VLucet** [comment]
Yes it does resolve it! (I used poetry wth `poetry add protobuf==3.20.1`).

I am not sure whether you ideally want 4+. If you're fine with 3.20 I can open a PR on the toml and lock file if you'd like.

**Comment by bencevans** [comment]
Fab. A PR would be fantastic!
